project:
  type: website
  output-dir: docs
website:
  title: "Dr. Mark Dunning - Bioinformatician / Data Scientist"
  google-analytics: 
    tracking-id: "G-96TB60ETKS"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: training.qmd
        text: Training Materials


format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true

editor: visual

