project:
  type: website
  output-dir: docs
website:
  title: "Dr. Mark Dunning - Bioinformatician / Data Scientist"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: training.qmd
        text: Training


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

