if(!require(BiocManager)) install.packages("BiocManager")
BiocManager::install(c( "org.Hs.eg.db", 
         "RColorBrewer", 
         "DESeq2",
         "pheatmap",
         "rmarkdown",
         "clusterProfiler",
         "DOSE",
         "biomaRt",
         "dplyr",
          "readr",
          "stringr",
         "tidyr",
         "ggplot2",
         "GeneTonic",
         "ggupset",
         "ggridges",
         "enrichplot",
        "EnhancedVolcano",
        "apeglm",
        "pathview"),suppressUpdates=TRUE)
